version: "3.9"
services:
  shard-mongo:
    image: mongo
    container_name: shard-mongo
    restart: always
    privileged: true
    ports:
      - 36379:27017
    command: -f /data/configdb/mongod.conf
    networks:
     default:
       ipv4_address: 192.168.0.100
    volumes:
      - ./main/conf/mongod.conf:/data/configdb/mongod.conf
      - ./main/conf/mongo.keyfile:/data/configdb/mongo.keyfile
      - ./main/data/db:/data/db

  shard-mongo-rep:
    image: mongo
    container_name: shard-mongo-rep
    restart: always
    privileged: true
    ports:
      - 36380:27017
    command: -f /data/configdb/mongod.conf
    networks:
     default:
       ipv4_address: 192.168.0.101
    volumes:
      - ./rep/conf/mongod.conf:/data/configdb/mongod.conf
      - ./rep/conf/mongo.keyfile:/data/configdb/mongo.keyfile
      - ./rep/data/db:/data/db

  shard-mongo-rep1:
    image: mongo
    container_name: shard-mongo-rep1
    restart: always
    privileged: true
    ports:
      - 36381:27017
    command: -f /data/configdb/mongod.conf
    networks:
     default:
       ipv4_address: 192.168.0.102
    volumes:
      - ./rep1/conf/mongod.conf:/data/configdb/mongod.conf
      - ./rep1/conf/mongo.keyfile:/data/configdb/mongo.keyfile
      - ./rep1/data/db:/data/db
networks:
  default:
    name: net
    external: true
