version: "3.9"
services:
  config-mongo:
    image: mongo
    container_name: config-mongo
    restart: always
    privileged: true
    command: -f /data/configdb/mongod.conf
    network_mode: "host"
    volumes:
      - ./main/conf/mongod.conf:/data/configdb/mongod.conf
      - ./main/conf/mongo.keyfile:/data/configdb/mongo.keyfile
      - ./main/data/db:/data/db

  config-mongo-rep:
    image: mongo
    container_name: config-mongo-rep
    restart: always
    privileged: true
    command: -f /data/configdb/mongod.conf
    network_mode: "host"
    volumes:
      - ./rep/conf/mongod.conf:/data/configdb/mongod.conf
      - ./rep/conf/mongo.keyfile:/data/configdb/mongo.keyfile
      - ./rep/data/db:/data/db

  config-mongo-rep1:
    image: mongo
    container_name: config-mongo-rep1
    restart: always
    privileged: true
    command: -f /data/configdb/mongod.conf
    network_mode: "host"
    volumes:
      - ./rep1/conf/mongod.conf:/data/configdb/mongod.conf
      - ./rep1/conf/mongo.keyfile:/data/configdb/mongo.keyfile
      - ./rep1/data/db:/data/db
