version: "3.9"
services:
  route-mongo:
    image: mongo
    container_name: route-mongo
    restart: always
    privileged: true
    command: mongos -f /data/configdb/mongos.conf
    network: "host"
    volumes:
      - ./main/conf/mongos.conf:/data/configdb/mongos.conf
