version: "3.9"
services:
  shard2-mongo:
    image: mongo
    container_name: shard2-mongo
    restart: always
    privileged: true
    command: -f /data/configdb/mongod.conf
    network_mode: "host"
    volumes:
      - ./main/conf/mongod.conf:/data/configdb/mongod.conf
      - ./main/data/db:/data/db

  shard2-mongo-rep:
    image: mongo
    container_name: shard2-mongo-rep
    restart: always
    privileged: true
    command: -f /data/configdb/mongod.conf
    network_mode: "host"
    volumes:
      - ./rep/conf/mongod.conf:/data/configdb/mongod.conf
      - ./rep/data/db:/data/db

  shard2-mongo-rep1:
    image: mongo
    container_name: shard2-mongo-rep1
    restart: always
    privileged: true
    command: -f /data/configdb/mongod.conf
    network_mode: "host"
    volumes:
      - ./rep1/conf/mongod.conf:/data/configdb/mongod.conf
      - ./rep1/data/db:/data/db
